cache:
  key: ${CI_JOB_NAME}
  paths:
    - conan

variables:
  CONAN_USER_HOME: "$CI_PROJECT_DIR/conan"

.ubuntu-20.04-amd64:
  image: ubuntu:20.04
  only:
    - master
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y gcc g++ cmake python3 python3-pip
    - pip3 install conan
    - mkdir -p $CI_PROJECT_DIR/build-ubuntu-20.04-amd64
    - cd $CI_PROJECT_DIR/build-ubuntu-20.04-amd64
    - conan install ../ --build missing --profile ../util/ci/gcc-release -o opencv=True

build-ubuntu-20.04-amd64:
  extends: .ubuntu-20.04-amd64
  stage: build
  script:
    - cmake ../ -DCMAKE_BUILD_TYPE=Release
    - make -j4
  artifacts:
    name: executables
    paths:
      - build-ubuntu-20.04-amd64/src/atmoctrl/atmoctrl
      - build-ubuntu-20.04-amd64/src/atmolight/atmolight

test-ubuntu-20.04-amd64:
  extends: .ubuntu-20.04-amd64
  stage: test
  script:
    - pip3 install gcovr
    - cmake ../ -DCMAKE_BUILD_TYPE=Release
    - make -j4
    - make test
  artifacts:
    name: coverage
    paths:
      - build-ubuntu-20.04-amd64/coverage